spring:
  profiles:
    active: pro
  thymeleaf:
      prefix: classpath:/templates/
  output:
    ansi:
      enabled: detect #终端彩色输出
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
  devtools:
    remote:
      restart:
        enabled: true
    restart:
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**
  jackson:
    time-zone: GMT+8 #设置request和response标准时间
    date-format: yyyy-MM-dd HH:mm:ss #设置时间格式
  servlet:
    multipart:
      max-file-size: 10MB #设置单个文件上传最大限制
      max-request-size: 100MB #设置单次请求上传最大限制


management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露所有端口



logging:
  file: log/my.log
  level:
    com.qjd.rry: debug #日志级别
# JWT
jwt:
  header: Authorization
  secret: maoyaoSecret
  expiration: 604800 #6048000000 #7天
  refresh:
    expiration: 6048000 #70天
  tokenHead: "Bearer "
  route:
    authentication:
      path: gettoken
      refresh: refresh
      register: register
      logout: logout

#付费推广刷新时间间隔(min)，目前已配置在数据库
refresh:
   interval: 30

#微信相关参数
wx:
  appid: wx9e********fd8032
  appsecret: 1b07f6**********4a1277c6afb03a14
  redirect:******maoyaoh5.********.com/auth/callback
  scope: snsapi_login
  pubAppId: wx********ba0295fe
  pubAppSecret: d08b4f**********82575328a9a888bdd
  pubRedirect:
    url: http://******h5.********.com/auth/callback
  public:
    url: caixinet


#QQ相关参数
QQ:
  appid: 1******28
  appkey: 9ca215********fac733ae6ec6de919b
  redirect:
      url: http://******h5.*********.com/auth/callback
  scope: snsapi_userinfo

#七牛相关配置
qiniu:
  accessKey: v7c5-9PurC**********9fpAXbzVA5VrBRW1mklD
  secretKey: sQK8mWll**********1RjZtlN_Jvgxomn3DmquDK
  bucket: maoyao
  path: file.******.com

#微吼相关配置
weihou:
  pass: ******
  appkey: 9dc018baafff4********49feed6aa3b
  secretkey: ff2bcf58d53ac********b3eb3848be2
  appsecretkey: c12e40f0f90600********9961e81175
  account: v*******
  password: ******

user:
  default:
    avatar: http://file.caixinet.com/1_1528176949158_专栏占位图.png #用户默认头像
    propump: 0.33


db_0:
  url: jdbc:mysql://*********/maoyao_0?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  username: xiaoyu
  password: ******
db_1:
  url: jdbc:mysql://*********/maoyao_1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  username: xiaoyu
  password: ******
