ALTER TABLE maoyao.user_auths AUTO_INCREMENT = 123456 ;
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$vgV3qwoWKp7Uq2R1z/F9IOSgcn4GCejiGWlAEfse.rjLpaaD6CCxi', CURRENT_TIMESTAMP(), 'root');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$GI8xvr2fm6D1UWAjFRS2wer8VqWwZICOuXA8qgDQrnEiPQLxhQ3i.', CURRENT_TIMESTAMP(), 'dingningchuan');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$ZgYTp7dfr325UmLFTVfNFeJk7Xx/IPaUxAeRO5.2JXyy3j7el/fr6', CURRENT_TIMESTAMP(), 'chenyingliang');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$7drLUhtslsoOvPIuEwvhFegefSRsYYMoLtA.MdNEdfFI34uq7//AK', CURRENT_TIMESTAMP(), 'zhaolichen');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$Gw98d9Tb.ITUm4aXS2cUge8E3zcGaArz/oE497EcjiCHHJl8EfsxK', CURRENT_TIMESTAMP(), 'dengyu');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$j.ueIfuEcMq1C/vcHsYTB.wnA/uSuQ/6IzqHsyUQR54QYjsxTmZZ2', CURRENT_TIMESTAMP(), 'chaomanrong');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$5sJtcTFDboNUzfF0sXNzx.C/q4tQy0//D91BFa8Rr8ahX.ubpHdLW', CURRENT_TIMESTAMP(), 'huangyongwen');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$zrTa7Tsg17FWfA/sVl7ms.r0XJpPGlTR0NUSZmiptapqrJAaU/d1y', CURRENT_TIMESTAMP(), 'wangzhenfeng');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$Ji/s9g6Q2Bvx150Dhomgz.XgjVzurK2TbVAlviWJWjCzjSX3xLNuq', CURRENT_TIMESTAMP(), 'liufang');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$/4uaLFEdJFSbSTketaO7sOm.2zCS5xXdM6C2q80qPbOxa0u6qldBy', CURRENT_TIMESTAMP(), 'liuwei');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$etZ27daWyMna8jMgzcynwOicoJ.anknd3Je26nKIi.7Tb7jtGu7FC', CURRENT_TIMESTAMP(), 'lixia');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$/MNTbuegKHBYZPQmXL8/Q.Z2VqJmg8308MqlgV5CjqZdbdtt6HrF.', CURRENT_TIMESTAMP(), 'huangcaixia');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$yF9Ar7JDLJzHNsTWfplfjOemE.vIBqCj.8JiwoedxR1/m1kG88fkW', CURRENT_TIMESTAMP(), 'wanhongwei');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$AN/anHgA2.VbyTD6jvLQaujC9.9s0UsG6P4GyStdJ.C/rFri4DTfu', CURRENT_TIMESTAMP(), 'hanbing');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$lLdg5qjSZcMJAOkqfObRi.6niVaOreijcULQtBGZO.1g/SwgeZ0xG', CURRENT_TIMESTAMP(), 'liuxinquan');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$G7NbKjixbHmTYqJu6cbbd.eH5HD54hR3oQPtXQM6kwLJiZotxfvWa', CURRENT_TIMESTAMP(), 'qudongbin');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$POUTOwk6V2BKD3AXg4Ydd.yasmqSf9HjuKWXDS8DKrCzapnA2uDoS', CURRENT_TIMESTAMP(), 'liguangyun');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$Cf5U1ZIx1yGnpxoqnJdgT.fTwxysj7GIF4bFtKasatyY.sf67wFdC', CURRENT_TIMESTAMP(), 'xiahong');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$hJQbEDP5.kj848pfO6Rkb.xaBtgVRrxMuTKMneDPYAxvcow6Cq4YO', CURRENT_TIMESTAMP(), 'chenlili');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$WMkHmgktv4LfTiiipDF63eGve3DPZViuUoOoUYSZRHj9x1y9YAbLe', CURRENT_TIMESTAMP(), 'liuxiuqing');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$QkGMMQR2UiakwEOLXUuDT.MJtBDjB5fryTXseLAe6AvrB2LNC1QgW', CURRENT_TIMESTAMP(), 'ligang');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$1jUEFbYkk2dBea8L.PmTAeB.GkzsreyHZhpHAZwF9djSyrcqYQc5q', CURRENT_TIMESTAMP(), 'zhangxueling');
INSERT INTO `maoyao`.`user_auths` (`create_time`, `identity_type`, `credential`, `update_time`, `identifier`) VALUES (CURRENT_TIMESTAMP(), '3', '$2a$10$kji.szfr4ziPQ90tGu/TfudL0KAX9AaRm3WYdM1zj/F7s4XU.8rRC', CURRENT_TIMESTAMP(), 'maxin');


