INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001', null, null, null, CURRENT_TIMESTAMP(), '艺术家分类', null, null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('002', null, null, null, CURRENT_TIMESTAMP(), '底部模块分类', null, null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('003', '0.8', null, null, CURRENT_TIMESTAMP(), 'VIP', null, null, 'vip权益介绍', null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('005', null, null, null, CURRENT_TIMESTAMP(), '课程/专栏推广', null, null, '推广说明', null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('006', '5', null, null, CURRENT_TIMESTAMP(), 'banner最大数量', null, null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('007', 'https://weidian.com/s/1324485459', null, null, CURRENT_TIMESTAMP(), '商城链接', null, null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001001', null, null, null, CURRENT_TIMESTAMP(), '国画', '001', 'http://file.caixinet.com/1_1528163262530_国画.png', null, '2', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001002', null, null, null, CURRENT_TIMESTAMP(), '油画', '001', 'http://file.caixinet.com/1_1528163298071_油画.png', null, '3', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001003', null, null, null, CURRENT_TIMESTAMP(), '素描', '001', 'http://file.caixinet.com/1_1528163323983_素描.png', null, '4', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001004', null, null, null, CURRENT_TIMESTAMP(), '水彩', '001', 'http://file.caixinet.com/1_1528163353192_水彩.png', null, '5', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001005', null, null, null, CURRENT_TIMESTAMP(), '手绘', '001', 'http://file.caixinet.com/1_1528163386491_手绘.png', null, '6', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001006', null, null, null, CURRENT_TIMESTAMP(), '手做', '001', 'http://file.caixinet.com/1_1528163411084_手做.png', null, '7', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001007', null, null, null, CURRENT_TIMESTAMP(), '雕塑', '001', 'http://file.caixinet.com/1_1528163442166_雕塑.png', null, '8', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001008', null, null, null, CURRENT_TIMESTAMP(), '艺考', '001', 'http://file.caixinet.com/1_1528163463799_艺考.png', null, '9', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001009', null, null, null, CURRENT_TIMESTAMP(), '书法', '001', 'http://file.caixinet.com/1_1528163481292_书法.png', null, '10', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001010', null, null, null, CURRENT_TIMESTAMP(), '设计', '001', 'http://file.caixinet.com/1_1528163514663_设计.png', null, '11', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001011', null, null, null, CURRENT_TIMESTAMP(), '民间艺术', '001', 'http://file.caixinet.com/1_1528163529415_民间艺术.png', null, '12', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`id`,`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('19','001012', null, null, null, CURRENT_TIMESTAMP(), '基础美术', '001', 'http://file.caixinet.com/1_1528163193013_基础美术.png', null, '1', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('002001', null, null, null, CURRENT_TIMESTAMP(), '使用指南', '002', 'http://file.caixinet.com/4_1528449727175_指南.png', null, null, null, 'http://www.caixinet.com/syzn.html', CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('002002', null, null, null, CURRENT_TIMESTAMP(), '服务说明', '002', 'http://file.caixinet.com/4_1528449784072_服务.png', null, null, null, 'http://www.caixinet.com/fwsm.html', CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('002003', null, null, null, CURRENT_TIMESTAMP(), '创建课程', '002', 'http://file.caixinet.com/4_1528449828927_创建课程.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('002004', null, null, null, CURRENT_TIMESTAMP(), '创建专栏', '002', 'http://file.caixinet.com/4_1528449874035_创建专栏.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('003000', null, null, null, CURRENT_TIMESTAMP(), '非vip', '003', null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('003001', null, null, null, CURRENT_TIMESTAMP(), '普通vip', '003', null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('003002', null, null, null, CURRENT_TIMESTAMP(), '超级vip', '003', null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('003003', null, null, null, CURRENT_TIMESTAMP(), '试用vip', '003', null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('003001001', '1', '388', null, CURRENT_TIMESTAMP(), '388元/年', '003001', null, null, null, 1, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('003001002', '6', '258', null, CURRENT_TIMESTAMP(), '258元/6个月', '003001', null, null, 2, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('003001003', '1', '50', null, CURRENT_TIMESTAMP(), '50元/月', '003001', null, null, null, 2, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('003003001', '7', '1', null, CURRENT_TIMESTAMP(), '1元/7天', '003003', null, null, null, 3, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('005001', '1', '5', null, CURRENT_TIMESTAMP(), '5元/次', '005', null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('005002', '5', '23', null, CURRENT_TIMESTAMP(), '23元/5次', '005', null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('005003', '10', '40', null, CURRENT_TIMESTAMP(), '40元/10次', '005', null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('005004', '20', '70', null, CURRENT_TIMESTAMP(), '70元/20次', '005', null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('005005', '50', '150', null, CURRENT_TIMESTAMP(), '150元/50次', '005', null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('004000', '0.2', '0.3', null, CURRENT_TIMESTAMP(), '平台抽取比例', null, null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面', null, null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('009', null , null , null, CURRENT_TIMESTAMP(), '默认专栏封面', null, null, null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008001', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面1', '008', 'http://file.caixinet.com/1_1536027263734_1.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008002', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面2', '008', 'http://file.caixinet.com/1_1536027278913_1.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008003', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面3', '008', 'http://file.caixinet.com/1_1536027288493_2.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008004', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面4', '008', 'http://file.caixinet.com/1_1536027300464_3.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008005', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面5', '008', 'http://file.caixinet.com/1_1536027310783_3c129bd33575a6fd1448676bd76abb0.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008006', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面6', '008', 'http://file.caixinet.com/1_1536027323460_4.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('009001', null , null , null, CURRENT_TIMESTAMP(), '默认专栏封面1', '009', 'http://file.caixinet.com/covers/3.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('009002', null , null , null, CURRENT_TIMESTAMP(), '默认专栏封面2', '009', 'http://file.caixinet.com/covers/3.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('009003', null , null , null, CURRENT_TIMESTAMP(), '默认专栏封面3', '009', 'http://file.caixinet.com/covers/3.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('009004', null , null , null, CURRENT_TIMESTAMP(), '默认专栏封面4', '009', 'http://file.caixinet.com/covers/3.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('009005', null , null , null, CURRENT_TIMESTAMP(), '默认专栏封面5', '009', 'http://file.caixinet.com/covers/3.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('009006', null , null , null, CURRENT_TIMESTAMP(), '默认专栏封面6', '009', 'http://file.caixinet.com/covers/3.png', null, null, null, null, CURRENT_TIMESTAMP());


/**
2018-08-28
 */
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001013', null, null, null, CURRENT_TIMESTAMP(), '演讲主持', '001', 'http://file.caixinet.com/1_1535428070413_演讲主持.jpg', null, '13', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001014', null, null, null, CURRENT_TIMESTAMP(), '美妆', '001', 'http://file.caixinet.com/1_1535428367168_美妆.jpg', null, '14', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001015', null, null, null, CURRENT_TIMESTAMP(), '音乐', '001', 'http://file.caixinet.com/1_1535428386296_音乐.jpg', null, '15', null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('001016', null, null, null, CURRENT_TIMESTAMP(), '舞蹈', '001', 'http://file.caixinet.com/1_1535428402553_舞蹈.jpg', null, '16', null, null, CURRENT_TIMESTAMP());

/**
2018-09-03
 */
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008007', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面7', '008', 'http://file.caixinet.com/1_1536027336995_5.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008008', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面8', '008', 'http://file.caixinet.com/1_1536027350998_5a70428a4da53.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008009', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面9', '008', 'http://file.caixinet.com/1_1536027362653_5aebc77f53fa3.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008010', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面10', '008', 'http://file.caixinet.com/1_1536027372371_5b1c748ebaf58.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008011', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面11', '008', 'http://file.caixinet.com/1_1536027383242_5b513b53243e0.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008012', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面12', '008', 'http://file.caixinet.com/1_1536027392015_6.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008013', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面13', '008', 'http://file.caixinet.com/1_1536027401121_8.24 03.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008014', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面14', '008', 'http://file.caixinet.com/1_1536027410481_8.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008015', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面15', '008', 'http://file.caixinet.com/1_1536027429943_8.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008016', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面16', '008', 'http://file.caixinet.com/1_1536027440759_8cfc018b36c512e9558ce812d1cbf04.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008017', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面17', '008', 'http://file.caixinet.com/1_1536027452031_9.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008018', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面18', '008', 'http://file.caixinet.com/1_1536027465162_11.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008019', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面19', '008', 'http://file.caixinet.com/1_1536027474128_12.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008020', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面20', '008', 'http://file.caixinet.com/1_1536027484653_33.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008021', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面21', '008', 'http://file.caixinet.com/1_1536027495447_80.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008022', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面22', '008', 'http://file.caixinet.com/1_1536027551304_02101ddb42adcca4cb690b315c13877.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008023', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面23', '008', 'http://file.caixinet.com/1_1536027564065_83003-可用.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008024', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面24', '008', 'http://file.caixinet.com/1_1536027574639_f2bb02007da1e69ffdd28a8860f11b4.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008025', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面25', '008', 'http://file.caixinet.com/1_1536027588086_fcf80970e8b787df513d3da81b068dc.png', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008026', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面26', '008', 'http://file.caixinet.com/1_1536027598403_海报082902.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008027', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面27', '008', 'http://file.caixinet.com/1_1536027607607_猫腰海报8.jpg', null, null, null, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('008028', null , null , null, CURRENT_TIMESTAMP(), '默认课程封面28', '008', 'http://file.caixinet.com/1_1536027616994_未标题-1.jpg', null, null, null, null, CURRENT_TIMESTAMP());

INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('011001', '1' , '365' , '1', CURRENT_TIMESTAMP(), '1张单价/365', '011', null, null, null, 1, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('011002', '1' , '335' , '5', CURRENT_TIMESTAMP(), '5张单价/335', '011', null, null, null, 1, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('011003', '1' , '300' , '10', CURRENT_TIMESTAMP(), '10张单价/300', '011', null, null, null, 1, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('011004', '1' , '250' , '20', CURRENT_TIMESTAMP(), '20张单价/250', '011', null, null, null, 1, null, CURRENT_TIMESTAMP());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `context3`, `create_time`, `name`, `p_code`, `purl`, `remark`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('011', '1' , null , null, CURRENT_TIMESTAMP(), null, null, null, null, null, 1, null, CURRENT_TIMESTAMP());


INSERT INTO `maoyao`.`category` (`code`, `create_time`, `name`, `update_time`) VALUES ('012', now(), '苹果内购VIP', now());
INSERT INTO `maoyao`.`category` (`code`, `create_time`, `name`, `p_code`, `update_time`) VALUES ('012000', now(), '非VIP', '012', now());
INSERT INTO `maoyao`.`category` (`code`, `create_time`, `name`, `p_code`, `update_time`) VALUES ('012001', now(), '普通VIP', '012', now());
INSERT INTO `maoyao`.`category` (`code`, `create_time`, `name`, `p_code`, `update_time`) VALUES ('012002', now(), '超级VIP', '012', now());
INSERT INTO `maoyao`.`category` (`code`, `create_time`, `name`, `p_code`, `update_time`) VALUES ('012003', now(), '试用VIP', '012', now());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `create_time`, `name`, `p_code`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('012001001', '1', '50', now(), '一个月VIP', '012001', '3', '2', 'com.Shanghai.JiZhi.MaoYaoLive.009', now());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `create_time`, `name`, `p_code`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('012001002', '1', '388', now(), '一年VIP', '012001', '1', '1', 'com.Shanghai.JiZhi.MaoYaoLive.007', now());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `create_time`, `name`, `p_code`, `sequence`, `time_type`, `turl`, `update_time`,`is_display`) VALUES ('012001003', '1', '273', now(), ' 一年VIP折扣', '012001', null, '1', 'com.Shanghai.JiZhi.MaoYaoLive.011', now(),b'0');
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `create_time`, `name`, `p_code`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('012001004', '7', '1', now(), '七天VIP', '012003', '4', '3', 'com.Shanghai.JiZhi.MaoYaoLive.010', now());
INSERT INTO `maoyao`.`category` (`code`, `context1`, `context2`, `create_time`, `name`, `p_code`, `sequence`, `time_type`, `turl`, `update_time`) VALUES ('012001005', '6', '258', now(), '半年VIP', '012001', '2', '2', 'com.Shanghai.JiZhi.MaoYaoLive.008',now());